# Generated by Django 4.2.30 on 2026-08-28 23:24

from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_client_contact_installation_installationcontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationType',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_lock', models.PositiveIntegerField(db_column='version_lock', default=1)),
                ('code', models.CharField(db_column='code', max_length=100, unique=True)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
            ],
            options={
                'db_table': '"master"."installation_types"',
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='installation',
                    table='"master"."installations"',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='servicecatalog',
                    table='"master"."service_catalog"',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='servicecatalogversion',
                    table='"master"."service_catalog_versions"',
                ),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCatalogInstallationType',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_lock', models.PositiveIntegerField(db_column='version_lock', default=1)),
                ('installation_type', models.ForeignKey(db_column='installation_type_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_catalog_links', to='master.installationtype')),
                ('service_catalog', models.ForeignKey(db_column='service_catalog_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='installation_type_links', to='master.servicecatalog')),
            ],
            options={
                'db_table': '"master"."service_catalog_installation_types"',
            },
        ),
        migrations.AddField(
            model_name='installation',
            name='installation_type',
            field=models.ForeignKey(blank=True, db_column='installation_type_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='installations', to='master.installationtype'),
        ),
        migrations.AddConstraint(
            model_name='servicecataloginstallationtype',
            constraint=models.UniqueConstraint(fields=('service_catalog', 'installation_type'), name='service_catalog_installation_types_unique'),
        ),
    ]
