# Generated by Django 4.2.30 on 2026-09-07 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_installationtype_alter_installation_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='installations', to='master.client'),
        ),
    ]
