from decimal import Decimal

from django.db import migrations, models
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Agreement",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid6.uuid7,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                            ),
                        ),
                        (
                            "version_lock",
                            models.PositiveIntegerField(
                                db_column="version_lock",
                                default=1,
                            ),
                        ),
                        (
                            "agreement_number",
                            models.CharField(
                                db_column="agreement_number",
                                max_length=50,
                            ),
                        ),
                        (
                            "quotation_id",
                            models.UUIDField(
                                db_column="quotation_id",
                            ),
                        ),
                        (
                            "opportunity_id",
                            models.UUIDField(
                                db_column="opportunity_id",
                            ),
                        ),
                        (
                            "client_id",
                            models.UUIDField(
                                db_column="client_id",
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("DRAFT", "Draft"),
                                    (
                                        "PENDING_SIGNATURE",
                                        "Pending signature",
                                    ),
                                    ("SIGNED", "Signed"),
                                    ("ACTIVE", "Active"),
                                    ("EXPIRED", "Expired"),
                                    ("TERMINATED", "Terminated"),
                                ],
                                db_column="status",
                                max_length=17,
                            ),
                        ),
                        (
                            "signed_by",
                            models.UUIDField(
                                blank=True,
                                db_column="signed_by",
                                null=True,
                            ),
                        ),
                        (
                            "signed_at",
                            models.DateTimeField(
                                blank=True,
                                db_column="signed_at",
                                null=True,
                            ),
                        ),
                        (
                            "effective_from",
                            models.DateField(
                                blank=True,
                                db_column="effective_from",
                                null=True,
                            ),
                        ),
                        (
                            "effective_until",
                            models.DateField(
                                blank=True,
                                db_column="effective_until",
                                null=True,
                            ),
                        ),
                        (
                            "terms_hash",
                            models.CharField(
                                blank=True,
                                db_column="terms_hash",
                                max_length=128,
                                null=True,
                            ),
                        ),
                        (
                            "notes",
                            models.TextField(
                                blank=True,
                                db_column="notes",
                                null=True,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "agreements",
                    },
                ),
                migrations.CreateModel(
                    name="AgreementTerm",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid6.uuid7,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                            ),
                        ),
                        (
                            "version_lock",
                            models.PositiveIntegerField(
                                db_column="version_lock",
                                default=1,
                            ),
                        ),
                        (
                            "agreement_id",
                            models.UUIDField(
                                db_column="agreement_id",
                            ),
                        ),
                        (
                            "term_code",
                            models.CharField(
                                db_column="term_code",
                                max_length=50,
                            ),
                        ),
                        (
                            "term_description",
                            models.TextField(
                                db_column="term_description",
                            ),
                        ),
                        (
                            "is_mandatory",
                            models.BooleanField(
                                db_column="is_mandatory",
                                default=True,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "agreement_terms",
                    },
                ),
                migrations.CreateModel(
                    name="CapacityAssessment",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid6.uuid7,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                            ),
                        ),
                        (
                            "version_lock",
                            models.PositiveIntegerField(
                                db_column="version_lock",
                                default=1,
                            ),
                        ),
                        (
                            "service_request_id",
                            models.UUIDField(
                                db_column="service_request_id",
                            ),
                        ),
                        (
                            "assessment_number",
                            models.CharField(
                                db_column="assessment_number",
                                max_length=50,
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("DRAFT", "Draft"),
                                    (
                                        "PENDING_REVIEW",
                                        "Pending review",
                                    ),
                                    ("APPROVED", "Approved"),
                                    ("REJECTED", "Rejected"),
                                    ("EXPIRED", "Expired"),
                                ],
                                db_column="status",
                                max_length=18,
                            ),
                        ),
                        (
                            "assessed_by",
                            models.UUIDField(
                                blank=True,
                                db_column="assessed_by",
                                null=True,
                            ),
                        ),
                        (
                            "assessed_at",
                            models.DateTimeField(
                                blank=True,
                                db_column="assessed_at",
                                null=True,
                            ),
                        ),
                        (
                            "technical_capacity",
                            models.BooleanField(
                                blank=True,
                                db_column="technical_capacity",
                                null=True,
                            ),
                        ),
                        (
                            "personnel_capacity",
                            models.BooleanField(
                                blank=True,
                                db_column="personnel_capacity",
                                null=True,
                            ),
                        ),
                        (
                            "equipment_capacity",
                            models.BooleanField(
                                blank=True,
                                db_column="equipment_capacity",
                                null=True,
                            ),
                        ),
                        (
                            "schedule_capacity",
                            models.BooleanField(
                                blank=True,
                                db_column="schedule_capacity",
                                null=True,
                            ),
                        ),
                        (
                            "observations",
                            models.TextField(
                                blank=True,
                                db_column="observations",
                                null=True,
                            ),
                        ),
                        (
                            "rejection_reason",
                            models.TextField(
                                blank=True,
                                db_column="rejection_reason",
                                null=True,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "capacity_assessments",
                    },
                ),
                migrations.CreateModel(
                    name="Opportunity",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid6.uuid7,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                            ),
                        ),
                        (
                            "version_lock",
                            models.PositiveIntegerField(
                                db_column="version_lock",
                                default=1,
                            ),
                        ),
                        (
                            "opportunity_number",
                            models.CharField(
                                db_column="opportunity_number",
                                max_length=50,
                            ),
                        ),
                        (
                            "service_request_id",
                            models.UUIDField(
                                db_column="service_request_id",
                            ),
                        ),
                        (
                            "client_id",
                            models.UUIDField(
                                db_column="client_id",
                            ),
                        ),
                        (
                            "assigned_to",
                            models.UUIDField(
                                blank=True,
                                db_column="assigned_to",
                                null=True,
                            ),
                        ),
                        (
                            "title",
                            models.CharField(
                                db_column="title",
                                max_length=255,
                            ),
                        ),
                        (
                            "description",
                            models.TextField(
                                blank=True,
                                db_column="description",
                                null=True,
                            ),
                        ),
                        (
                            "estimated_value",
                            models.DecimalField(
                                blank=True,
                                db_column="estimated_value",
                                decimal_places=2,
                                max_digits=14,
                                null=True,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "opportunities",
                    },
                ),
                migrations.CreateModel(
                    name="Quotation",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid6.uuid7,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                            ),
                        ),
                        (
                            "version_lock",
                            models.PositiveIntegerField(
                                db_column="version_lock",
                                default=1,
                            ),
                        ),
                        (
                            "quotation_number",
                            models.CharField(
                                db_column="quotation_number",
                                max_length=50,
                            ),
                        ),
                        (
                            "opportunity_id",
                            models.UUIDField(
                                db_column="opportunity_id",
                            ),
                        ),
                        (
                            "client_id",
                            models.UUIDField(
                                db_column="client_id",
                            ),
                        ),
                        (
                            "issued_by",
                            models.UUIDField(
                                db_column="issued_by",
                            ),
                        ),
                        (
                            "issue_date",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_column="issue_date",
                            ),
                        ),
                        (
                            "valid_until",
                            models.DateField(
                                blank=True,
                                db_column="valid_until",
                                null=True,
                            ),
                        ),
                        (
                            "subtotal",
                            models.DecimalField(
                                db_column="subtotal",
                                decimal_places=2,
                                default=Decimal("0"),
                                max_digits=14,
                            ),
                        ),
                        (
                            "tax_amount",
                            models.DecimalField(
                                db_column="tax_amount",
                                decimal_places=2,
                                default=Decimal("0"),
                                max_digits=14,
                            ),
                        ),
                        (
                            "total_amount",
                            models.DecimalField(
                                db_column="total_amount",
                                decimal_places=2,
                                default=Decimal("0"),
                                max_digits=14,
                            ),
                        ),
                        (
                            "currency",
                            models.CharField(
                                db_column="currency",
                                default="MXN",
                                max_length=3,
                            ),
                        ),
                        (
                            "notes",
                            models.TextField(
                                blank=True,
                                db_column="notes",
                                null=True,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "quotations",
                    },
                ),
                migrations.CreateModel(
                    name="QuotationItem",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid6.uuid7,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                            ),
                        ),
                        (
                            "version_lock",
                            models.PositiveIntegerField(
                                db_column="version_lock",
                                default=1,
                            ),
                        ),
                        (
                            "quotation_id",
                            models.UUIDField(
                                db_column="quotation_id",
                            ),
                        ),
                        (
                            "service_catalog_id",
                            models.UUIDField(
                                db_column="service_catalog_id",
                            ),
                        ),
                        (
                            "description",
                            models.CharField(
                                db_column="description",
                                max_length=500,
                            ),
                        ),
                        (
                            "quantity",
                            models.DecimalField(
                                db_column="quantity",
                                decimal_places=3,
                                default=Decimal("1"),
                                max_digits=12,
                            ),
                        ),
                        (
                            "unit_price",
                            models.DecimalField(
                                db_column="unit_price",
                                decimal_places=2,
                                default=Decimal("0"),
                                max_digits=14,
                            ),
                        ),
                        (
                            "line_total",
                            models.DecimalField(
                                db_column="line_total",
                                decimal_places=2,
                                default=Decimal("0"),
                                max_digits=14,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "quotation_items",
                    },
                ),
                migrations.CreateModel(
                    name="ServiceRequest",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid6.uuid7,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                            ),
                        ),
                        (
                            "version_lock",
                            models.PositiveIntegerField(
                                db_column="version_lock",
                                default=1,
                            ),
                        ),
                        (
                            "client_id",
                            models.UUIDField(
                                db_column="client_id",
                            ),
                        ),
                        (
                            "installation_id",
                            models.UUIDField(
                                blank=True,
                                db_column="installation_id",
                                null=True,
                            ),
                        ),
                        (
                            "service_catalog_id",
                            models.UUIDField(
                                db_column="service_catalog_id",
                            ),
                        ),
                        (
                            "request_number",
                            models.CharField(
                                db_column="request_number",
                                max_length=50,
                            ),
                        ),
                        (
                            "requested_at",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_column="requested_at",
                            ),
                        ),
                        (
                            "requested_by_name",
                            models.CharField(
                                blank=True,
                                db_column="requested_by_name",
                                max_length=255,
                                null=True,
                            ),
                        ),
                        (
                            "requested_by_email",
                            models.CharField(
                                blank=True,
                                db_column="requested_by_email",
                                max_length=254,
                                null=True,
                            ),
                        ),
                        (
                            "requested_by_phone",
                            models.CharField(
                                blank=True,
                                db_column="requested_by_phone",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "request_description",
                            models.TextField(
                                blank=True,
                                db_column="request_description",
                                null=True,
                            ),
                        ),
                        (
                            "created_by",
                            models.UUIDField(
                                blank=True,
                                db_column="created_by",
                                null=True,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "service_requests",
                    },
                ),
            ],
        ),
    ]