# Generated by Django 4.2.30 on 2026-08-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_installationtype_alter_installation_table_and_more'),
        ('commercial', '0003_quotation_issued_by_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='installation_type',
            field=models.ForeignKey(blank=True, db_column='installation_type_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prospects', to='master.installationtype'),
        ),
    ]
