# Generated by Django 4.2.30 on 2026-08-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_prospect_installation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='issued_by',
            field=models.UUIDField(db_column='issued_by'),
        ),
    ]
