# Generated by Django 4.2.30 on 2026-09-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_alter_quotation_issued_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='prospect',
            field=models.ForeignKey(blank=True, db_column='prospect_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='commercial.prospect'),
        ),
    ]
