# Generated by Django 4.2.30 on 2026-09-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0013_harden_prospect_lifecycle_state'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='prospect',
                    name='installation_type',
                ),
                migrations.AlterField(
                    model_name='prospect',
                    name='status',
                    field=models.CharField(
                        choices=[
                            ('NEW', 'New'),
                            ('CONTACTED', 'Contacted'),
                            ('QUALIFIED', 'Qualified'),
                            ('QUOTED', 'Quoted'),
                            ('WON', 'Won'),
                            ('LOST', 'Lost'),
                            ('CONVERTED', 'Converted'),
                        ],
                        db_column='status',
                        default='NEW',
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
