# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commercial",
            "0016_commercialclausetemplate_commercialcomponenttype_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="agreement",
                    name="employer_registration",
                    field=models.CharField(
                        blank=True,
                        db_column="employer_registration",
                        max_length=50,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="agreement",
                    name="legal_name",
                    field=models.CharField(
                        blank=True,
                        db_column="legal_name",
                        max_length=255,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="agreement",
                    name="legal_representative_name",
                    field=models.CharField(
                        blank=True,
                        db_column="legal_representative_name",
                        max_length=255,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="agreement",
                    name="legal_representative_tax_id",
                    field=models.CharField(
                        blank=True,
                        db_column="legal_representative_tax_id",
                        max_length=13,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="agreement",
                    name="tax_id",
                    field=models.CharField(
                        blank=True,
                        db_column="tax_id",
                        max_length=13,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="quotationitem",
                    name="evaluation_period",
                    field=models.CharField(
                        blank=True,
                        db_column="evaluation_period",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
